name: Automate EAS Secrets and Build

on:
  push:
    branches:
      - main

jobs:
  automate-and-build:
    name: Automate Secrets and Build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Install EAS CLI
      - name: Install EAS CLI
        run: npm install -g eas-cli

      # Step 5: Encode GoogleService-Info.plist
      - name: Encode GoogleService-Info.plist
        run: base64 GoogleService-Info.plist > GoogleServiceInfo.b64

      # Step 6: Create EAS Secret
      - name: Create EAS Secret
        run: |
          eas env:create --environment production --name GOOGLE_SERVICE_INFO_PLIST --type file --value ./GoogleServiceInfo.b64 --scope project
          eas env:list --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      # Step 7: Run EAS Build
      - name: Run EAS Build
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --platform ios --non-interactive
