name: EAS Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build with EAS
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install EAS CLI
      - name: Install EAS CLI
        run: npm install -g eas-cli

      # Step 4: Set EAS Token
      - name: Set EAS Token
        run: echo "EXPO_TOKEN=${{ secrets.EXPO_TOKEN }}" >> $GITHUB_ENV

      # Step 5: Trigger EAS Build
      - name: Run EAS Build
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --platform ios --non-interactive
