name: EAS Build Workflow

on:
  push:
    branches:
      - main

jobs:
  automate-and-build:
    name: Automate Secrets and Build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Install EAS CLI
      - name: Install EAS CLI
        run: npm install -g eas-cli

      # Step 5: Make automate-secrets.sh Executable
      - name: Make Script Executable
        run: chmod +x ./automate-secrets.sh

      # Step 6: Run automate-secrets.sh
      - name: Run Automate Secrets Script
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: ./automate-secrets.sh

      # Step 7: Run EAS Build
      - name: Run EAS Build
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --platform ios --non-interactive --verbose
